### ISSUE TITLE
Algorithm.ldLBFGSNoCedal does not mean "no cedal"

### ISSUE THREAD

**Issue by tosttost** [jmh530/nloptd#1]
[Jorge Nocedal](http://users.iems.northwestern.edu/~nocedal/) is a living person. Therefore 
ldLBFSNocedal
may be a better name.

**Comment by jmh530** [comment]
Ah. Correction made, along with a few others that I had been meaning to push. I changed it to work with the dlangscience nlopt package instead of the libnlopt package I had created. I would appreciate further testing. I have not had much luck on Windows yet, I think I'll have to rebuild the dlls.
