### ISSUE TITLE
package naming

### ISSUE THREAD

**Issue by Sandman83** [jmh530/nloptd#2]
Hi! 
Could you name the "nloptd.d" file "package.d"? Would be nice for finding the package by the dub. 

Greetings
Alex

**Comment by jmh530** [comment]
Can you be a bit more specific about what your issue is?

I don't think there is any particular requirement that files in dub are named package.d. I looked through a few to double-check. 

Package.d can be helpful when you have many files and want to publicly import from a few of them as the face of the package.

**Comment by Sandman83** [comment]
sure. I have the error on recompilation, when the file is named nlopt.d the message is

libnlopt 0.2.0: target for configuration "libnlopt-library" is up to date.
nloptd 0.2.1: target for configuration "nloptd-library" is up to date.
source/Optimizer.d(7,8): Error: module nloptd is in file 'nloptd.d' which cannot be read
import path[0] = source/
import path[3] = ../../../../../../../.dub/packages/libnlopt-0.2.0/libnlopt/source/
import path[5] = ../../../../../../../.dub/packages/nloptd-0.2.1/nloptd/source/
import path[7] = /usr/local/Cellar/dmd/2.071.1/include/dlang/dmd

Seems strange, I know, as the file nloptd.d is there, still it couldn't be found. 
And if I rename it manually to "package.d" inside the ~/.dub/... folder and recompile my project the error is not there any more and everything compiles...

Maybe something is wrong at my side?

**Comment by jmh530** [comment]
Can you verify that you nloptd has been included properly, either as a dependency to your dub project or with -I? The below references may be informative.

http://stackoverflow.com/questions/27573909/module-x-is-in-x-d-which-cannot-be-read-error-when-compiling-a-d-program
http://stackoverflow.com/questions/20888257/gdc-error-error-module-file-is-in-file-file-d-which-cannot-be-read

**Comment by Sandman83** [comment]
yes, I have 
"libnlopt": "~>0.2.0",
"nloptd": "~>0.2.1"
in my dub.json
